spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:phoenix_login}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update

jwt:
  secret: ${JWT_KEY}