spring:
  mail:
    host: ${HOST:premium74.web-hosting.com}
    port: ${PORT:587}
    username: ${dbusername}
    password: ${dbpassword}
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enabled: true

demo:
  test-value: Added dependency to config server v.90.9 build 990